### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by mfulton26** [zemirco/json2csv-stream#17]
Similar to json2csv it would be great if the streaming support could be exposed via a command line tool. I have some very large JSON documents that I get periodically and json2csv works great but is rather slow but I suspect it would be faster if it were streamed from stdin to stdout (or to a file). Thanks.

**Comment by knownasilya** [comment]
Have a look out for a new release of `json2csv` which now includes streaming support (the cli streams by default). This library will be deprecated.

**Comment by mfulton26** [comment]
Sweet.

**Comment by mfulton26** [comment]
Should that solve the following problem I just ran into?

```
/usr/lib/node_modules/json2csv/lib/json2csv.js:330
      Array.prototype.push.apply(dataRows, dataRow);
                           ^

RangeError: Maximum call stack size exceeded
    at /usr/lib/node_modules/json2csv/lib/json2csv.js:330:28
    at Array.forEach (native)
    at createDataRows (/usr/lib/node_modules/json2csv/lib/json2csv.js:323:18)
    at createColumnContent (/usr/lib/node_modules/json2csv/lib/json2csv.js:209:3)
    at module.exports (/usr/lib/node_modules/json2csv/lib/json2csv.js:60:13)
    at /usr/lib/node_modules/json2csv/bin/json2csv.js:136:15
    at getInput (/usr/lib/node_modules/json2csv/bin/json2csv.js:60:12)
    at /usr/lib/node_modules/json2csv/bin/json2csv.js:104:3
    at getFields (/usr/lib/node_modules/json2csv/bin/json2csv.js:49:5)
    at Object.<anonymous> (/usr/lib/node_modules/json2csv/bin/json2csv.js:99:1)
```

**Comment by knownasilya** [comment]
Yes, if you use the stream API. You can test it now using the master branch.

**Comment by mfulton26** [comment]
Oh, I used the master branch of json2csv-stream, I'll try json2csv, my mistake. Thanks.
